PR for adding Open Rec to badminton schedule
williamshen-nz/recschedule-website pull request #3
Opened 2022-10-13 01:45 UTC by aoranwu

Hi William,

I add two features to the codebase:

1. Add a parameter include_shared_open_rec to optionally include courts marked as Open Rec (only for du Pont DU PONT CT1/CT2 and Rockwell SOUTH CT/Rockwell NORTH CT) to the badminton schedule.
2. Sort schedule by (start_time, end_time, location). For each individual time use ("AM/PM", hh, mm) as the key to sort.

I also add unit tests with the original test file as the input.

Besides, I tried out question mark tooltip but cannot make it work. So I add a * and a line for explanation instead.

Feel free to change the UI if you feel there's a better way to put the message.

Aoran

2022-10-13 02:08 UTC, williamshen-nz commented
Thanks for your contribution Aoran - great work! 

I've deployed your code in the meantime at https://shen.nz/badminton-beta/

I will review your PR sometime this weekend and add some comments.

2022-10-14 15:01 UTC, williamshen-nz requested changes
Thanks for the changes - left some minor comments. Could you please address them?

Also, could you please run isort and black so the code formatting is more consistent?

```
pip install isort black
isort --profile black . && black .
```

I'll then merge it in and do some fixes on my end.

2022-10-14 15:01 UTC, williamshen-nz commented on main.py
> +            len(sys.argv) == 3
Can you run black and isort on all the code? They are autoformatters to keep code consistent.

```
> pip install black isort
> isort . --profile black && black .
```

2022-10-14 15:01 UTC, williamshen-nz commented on recschedule_website/parser.py
> +)
I think you could collapse these regexes into one?

```
(\d{1,2}:\d{2})\s(AM|PM)\s+(\d{1,2}:\d{2})\s(AM|PM)\s+.*(Open Rec|Open Recreation) \s+(.*)
```

2022-10-14 15:01 UTC, williamshen-nz commented on recschedule_website/parser.py
> +def to_key(schedule: Schedule) -> bool:
No need to do this, but you could punt this to the Schedule object in the future

https://stackoverflow.com/a/48731059

2022-10-16 23:37 UTC, aoranwu commented on recschedule_website/parser.py
> +)
Done.

2022-10-16 23:37 UTC, aoranwu commented on recschedule_website/parser.py
> +def to_key(schedule: Schedule) -> bool:
Acknowleged.

2022-10-17 15:50 UTC, williamshen-nz approved these changes

2022-10-17 15:51 UTC, williamshen-nz commented
Thanks for addressing the comments - PR looks good to me so I'm going to merge!

I'll do some cleanup once I have more time (in 2 weeks or so) and merge it into live. For now, you can use the beta endpoint: https://shen.nz/badminton-beta/

2022-10-17 15:52 UTC, merged

2022-10-17 22:55 UTC, aoranwu commented
Glad to hear that!